---
# Create a new guest using Kickstart

- name: Show .ks file contents for debugging
  command: cat "{{ runtime_tempdir }}/{{ inventory_hostname }}.ks"
  register: ks_file
  become: true
  delegate_to: "{{ hyper }}"
  when: debug|bool

- name: Show .ks file contents for debugging
  debug:
    var: ks_file.stdout_lines
  when: debug|bool

...